name: Java CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: make build
      - run: make say-hello

#      - name: Publish code coverage
#        uses: paambaati/codeclimate-action@v3.0.0